### PR TITLE
Add quotes to MSBUILD_PATH usage in posh scripts

### PR DESCRIPTION
**Pull request by stuartleeks**
This seems to bring it inline with the batch script

### CODE REVIEW

**Comment by shibayan** [comment]
@stuartleeks it was no problem without a quotes. what is the problem?

**Comment by stuartleeks** [comment]
It failed for without quotes as the path to msbuild.exe on my machine contains spaces. It worked fine when enclosed in quotes.

**Comment by shibayan** [comment]
Well, I was understanding. Thank you for code fix.

**Comment by davidebbo** [comment]
Merged. Fix is in 1.0.6

**Pull request closed without merging**
