### PR TITLE
Add posh support for ASP.NET Core application

### PR DESCRIPTION
**Pull request by shibayan**
Added ASP.NET Core App posh deployment script.

### CODE REVIEW

**Comment by davidebbo** [comment]
Thanks @shibayan, change seems good. @ahmelsayed can you take a look and merge in if you don't find issues?

**Comment by ahmelsayed** [comment]
The change looks good to me. Have you had a chance to test it on azure to make sure it works there? I remember we had some trouble with launching exes from powershell last time, but they may have been fixed in the sandbox since then

**Comment by shibayan** [comment]
@ahmelsayed Yes. I have confirmed the deployment script at Azure Web Apps. Already used in the my application.
https://github.com/shibayan/appserviceinfo

and Activity Logs is here.
https://gist.github.com/shibayan/5b32e46c62e01c8e502b1c6f2fb825ba

I also remember the previous error. I think the problem was can be avoided by changing the .deployment file.

**Comment by davidebbo** [comment]
It's on npm as kuduscript 1.0.8. It should make its way onto Kudu in the next week or so.

**Pull request merged**
